server {
    listen 80;
    server_name localhost;

    # Limite máximo de upload (corrige erro 413 Request Entity Too Large)
    client_max_body_size 500M;
    client_body_buffer_size 1M;

    # Assets ESM usados pelo PDF.js precisam ser servidos como JavaScript.
    location ~* \.mjs$ {
        root /usr/share/nginx/html;
        types {
            application/javascript mjs;
        }
        default_type application/javascript;
        try_files $uri =404;
    }

    # 1. FRONT-END (React/Vite)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. BACKEND (Spring Boot)
    location /hydro-flow/ {
        proxy_pass http://hydro-flow:8080/hydro-flow/;  # era thin-layer:9090/thin-layer/
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 300s;
        proxy_send_timeout    300s;
        proxy_read_timeout    300s;
        proxy_request_buffering off;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
