name: CI Pipeline - Frontend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build e Validação
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o download do código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Instala e configura o pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 

      # 3. Configura o Node.js com cache para o pnpm (acelera as execuções futuras)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # 4. Instala as dependências do projeto
      - name: Instalar dependências
        run: pnpm install --frozen-lockfile

      # 5. Validação de Qualidade de Software (Opcional, mas recomendado)
      - name: Análise estática (Linting)
        run: pnpm run lint
      #
      - name: Testes Automatizados
        run: pnpm run test

      # 6. Faz o build da aplicação Vite
      - name: Build da aplicação
        run: pnpm run build